### ISSUE TITLE
images not showing after building with vercel.com

### ISSUE THREAD

**Issue by shaaanuu** [shaaanuu/react-shopping-cart#1]
The images are not showing. All the images are present in src/assets/ folder.
The images were shown before the build.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this

**Comment by shaaanuu** [comment]
Yeah

**Comment by Pooja1672** [comment]
Hi @shaaanuu , I would like to work on this issue

**Comment by shaaanuu** [comment]
Does  anyone know why this happens?
